<h1><?php echo "Crear Equipo"; ?></h1>
<hr/>

<form class="form-inline" action="" method="POST" enctype="multipart/form-data">
  <div class="form-group col-xs-12">
    <label for="name">Nombre</label>
    <input type="text" class="form-control" name="name" id="name">
  </div>
  <div class="form-group col-xs-12">
    <label for="image">imagen</label>
    <input type="file" class="file-path" name="image" id="image">
  </div>
  <div class="form-group col-xs-12">
  	<br>
    <select name="status" class="form-control">
          <option value="1">Activo</option>
          <option value="0">Innactivo</option>
    </select>
  </div>
  <div class="form-group col-xs-12" >
  		<br>
  		<button type="submit" class="btn btn-default">Submit</button>
  </div>
</form>