<h1>Listado de Equipos</h1>

<hr/>
<a class="btn btn-success" href="<?php echo $this->basePath("/equipo/add"); ?>">Crear equipo</a>

<hr/>



<?php 
$flash=$this->flashMessenger()
		->setMessageOpenFormat("<div%s>")
		->setMessageSeparatorString("")
		->setMessageCloseString("</div>");

echo $flash->render("add",array("alert","alert-success"));
echo $flash->render("add_false",array("alert","alert-danger"));
?>

<table class="table table-hover table-striped">
	<tr>
		<th>Logo</th>
		<th>Nombre</th>
		<th>Estatus</th>
		<th colspan="2">Acciones</th>
	</tr>
	<?php foreach ($this->equipos as $equipo){ ?>
	<tr>
		<td><img src="<?php echo $this->basePath("img/teams/".$equipo->equipo_logo) ?>" class="img-team-logo"></td>
		<td><?php echo $equipo->equipo_name; ?></td>
		<td>
			<?php if($equipo->equipo_status == 1){	echo "Activo" ; } ;?> 
			<?php  if($equipo->equipo_status == 0){ echo "Suspendido" ;} ;?>
		</td>
		
		<!--td><a class="btn btn-warning" href="<?php echo $this->basePath("/usuario/edit/".$usuario->id); ?>">Editar</a></td-->
		<td><a class="btn btn-info" href="<?php echo $this->basePath("/jugador/detail/".$equipo->equipo_id); ?>">Ver</a></td>
		<td><a class="btn btn-danger" href="<?php echo $this->basePath("/equipo/delete/".$equipo->equipo_id); ?>">Eliminar</a></td>
		
	</tr>
	<?php } ?>
</table>

<?php 
 echo $this->paginationControl(
		 $this->equipos,
		 "sliding",
		 "partial/paginator.phtml",
		 array(
			 "route" => "equipo"
		 ));
?>


